name: Build & publish changed images

on:
  push:
    branches:
    - main

jobs:

  detect_image_source_changes:
    runs-on: ubuntu-latest
    outputs:
      node-12-on-ubuntu-focal_changed: ${{ steps.changes_to_node-12-on-ubuntu-focal.outputs.any_changed == 'true' || steps.changes_to_node-12-on-ubuntu-focal.outputs.any_deleted == 'true' }}
      node-14-on-ubuntu-focal_changed: ${{ steps.changes_to_node-14-on-ubuntu-focal.outputs.any_changed == 'true' || steps.changes_to_node-14-on-ubuntu-focal.outputs.any_deleted == 'true' }}
      node-16-on-ubuntu-focal_changed: ${{ steps.changes_to_node-16-on-ubuntu-focal.outputs.any_changed == 'true' || steps.changes_to_node-16-on-ubuntu-focal.outputs.any_deleted == 'true' }}
      openjdk-8-on-ubuntu-focal_changed: ${{ steps.changes_to_openjdk-8-on-ubuntu-focal.outputs.any_changed == 'true' || steps.changes_to_openjdk-8-on-ubuntu-focal.outputs.any_deleted == 'true' }}
      openjdk-11-on-ubuntu-focal_changed: ${{ steps.changes_to_openjdk-11-on-ubuntu-focal.outputs.any_changed == 'true' || steps.changes_to_openjdk-11-on-ubuntu-focal.outputs.any_deleted == 'true' }}
      python-27-on-ubuntu-focal_changed: ${{ steps.changes_to_python-27-on-ubuntu-focal.outputs.any_changed == 'true' || steps.changes_to_python-27-on-ubuntu-focal.outputs.any_deleted == 'true' }}
      python-39-on-ubuntu-focal_changed: ${{ steps.changes_to_python-39-on-ubuntu-focal.outputs.any_changed == 'true' || steps.changes_to_python-39-on-ubuntu-focal.outputs.any_deleted == 'true' }}
    steps:
    - uses: actions/checkout@v2
    - id: changes_to_node-12-on-ubuntu-focal
      uses: tj-actions/changed-files@v1.1.2
      with:
        files: node/node-12-on-ubuntu-focal
    - run: |
        echo '${{ toJSON(steps.changes_to_node-12-on-ubuntu-focal) }}'
    - id: changes_to_node-14-on-ubuntu-focal
      uses: tj-actions/changed-files@v1.1.2
      with:
        files: node/node-14-on-ubuntu-focal
    - id: changes_to_node-16-on-ubuntu-focal
      uses: tj-actions/changed-files@v1.1.2
      with:
        files: node/node-16-on-ubuntu-focal
    - id: changes_to_openjdk-8-on-ubuntu-focal
      uses: tj-actions/changed-files@v1.1.2
      with:
        files: openjdk/openjdk-8-on-ubuntu-focal
    - id: changes_to_openjdk-11-on-ubuntu-focal
      uses: tj-actions/changed-files@v1.1.2
      with:
        files: openjdk/openjdk-11-on-ubuntu-focal
    - id: changes_to_python-27-on-ubuntu-focal
      uses: tj-actions/changed-files@v1.1.2
      with:
        files: python/python-2.7-on-ubuntu-focal
    - id: changes_to_python-39-on-ubuntu-focal
      uses: tj-actions/changed-files@v1.1.2
      with:
        files: python/python-3.9-on-ubuntu-focal

  build_and_publish_node-12-on-ubuntu-focal:
    needs: detect_image_source_changes
    if: ${{ needs.detect_image_source_changes.outputs.node-12-on-ubuntu-focal_changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_publish_image
      with:
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: node/node-12-on-ubuntu-focal
        image_tag_1: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-node:20.04-12
        image_tag_2: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-node:focal-12

  build_and_publish_node-14-on-ubuntu-focal:
    needs: detect_image_source_changes
    if: ${{ needs.detect_image_source_changes.outputs.node-14-on-ubuntu-focal_changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/build_and_publish_image
      with:
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: node/node-14-on-ubuntu-focal
        image_tag_1: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-node:20.04-14
        image_tag_2: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-node:focal-14

  build_and_publish_node-16-on-ubuntu-focal:
    needs: detect_image_source_changes
    if: ${{ needs.detect_image_source_changes.outputs.node-16-on-ubuntu-focal_changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/build_and_publish_image
      with:
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: node/node-16-on-ubuntu-focal
        image_tag_1: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-node:20.04-16
        image_tag_2: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-node:focal-16

  build_and_publish_openjdk-8-on-ubuntu-focal:
    needs: detect_image_source_changes
    if: ${{ needs.detect_image_source_changes.outputs.openjdk-8-on-ubuntu-focal_changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/build_and_publish_image
      with:
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: openjdk/openjdk-8-on-ubuntu-focal
        image_tag_1: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-openjdk:20.04-8
        image_tag_2: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-openjdk:focal-8

  build_and_publish_openjdk-8-on-ubuntu-focal:
    needs: detect_image_source_changes
    if: ${{ needs.detect_image_source_changes.outputs.openjdk-11-on-ubuntu-focal_changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/build_and_publish_image
      with:
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: openjdk/openjdk-11-on-ubuntu-focal
        image_tag_1: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-openjdk:20.04-11
        image_tag_2: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-openjdk:focal-11

  build_and_publish_python-27-on-ubuntu-focal:
    needs: detect_image_source_changes
    if: ${{ needs.detect_image_source_changes.outputs.python-27-on-ubuntu-focal_changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/build_and_publish_image
      with:
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: python/python-2.7-on-ubuntu-focal
        image_tag_1: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-python:20.04-2.7
        image_tag_2: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-python:focal-2.7

  build_and_publish_python-39-on-ubuntu-focal:
    needs: detect_image_source_changes
    if: ${{ needs.detect_image_source_changes.outputs.python-39-on-ubuntu-focal_changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/build_and_publish_image
      with:
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: python/python-3.9-on-ubuntu-focal
        image_tag_1: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-python:20.04-3.9
        image_tag_2: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-python:focal-3.9
