name: Build & publish all images

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Sign in to GitHub Packages Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & publish spaces-ubuntu-node:20.04-12
        uses: docker/build-push-action@v2
        with:
          context: node/node-12-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-node:20.04-12
          push: true

      - name: Build & publish spaces-ubuntu-node:focal-12
        uses: docker/build-push-action@v2
        with:
          context: node/node-12-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-node:focal-12
          push: true

      - name: Build & publish spaces-ubuntu-node:20.04-14
        uses: docker/build-push-action@v2
        with:
          context: node/node-14-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-node:20.04-14
          push: true

      - name: Build & publish spaces-ubuntu-node:focal-14
        uses: docker/build-push-action@v2
        with:
          context: node/node-14-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-node:focal-14
          push: true

      - name: Build & publish spaces-ubuntu-node:20.04-16
        uses: docker/build-push-action@v2
        with:
          context: node/node-16-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-node:20.04-16
          push: true

      - name: Build & publish spaces-ubuntu-node:focal-16
        uses: docker/build-push-action@v2
        with:
          context: node/node-16-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-node:focal-16
          push: true

      - name: Build & publish spaces-ubuntu-openjdk:20.04-8
        uses: docker/build-push-action@v2
        with:
          context: openjdk/openjdk-8-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-openjdk:20.04-8
          push: true

      - name: Build & publish spaces-ubuntu-openjdk:focal-8
        uses: docker/build-push-action@v2
        with:
          context: openjdk/openjdk-8-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-openjdk:focal-8
          push: true

      - name: Build & publish spaces-ubuntu-openjdk:20.04-11
        uses: docker/build-push-action@v2
        with:
          context: openjdk/openjdk-11-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-openjdk:20.04-11
          push: true

      - name: Build & publish spaces-ubuntu-openjdk:focal-11
        uses: docker/build-push-action@v2
        with:
          context: openjdk/openjdk-11-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-openjdk:focal-11
          push: true

      - name: Build & publish spaces-ubuntu-python:20.04-2.7
        uses: docker/build-push-action@v2
        with:
          context: python/python-2.7-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-python:20.04-2.7
          push: true

      - name: Build & publish spaces-ubuntu-python:focal-2.7
        uses: docker/build-push-action@v2
        with:
          context: python/python-2.7-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-python:focal-2.7
          push: true

      - name: Build & publish spaces-ubuntu-python:20.04-3.6
        uses: docker/build-push-action@v2
        with:
          context: python/python-3.6-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-python:20.04-3.6
          push: true

      - name: Build & publish spaces-ubuntu-python:focal-3.6
        uses: docker/build-push-action@v2
        with:
          context: python/python-3.6-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-python:focal-3.6
          push: true

      - name: Build & publish spaces-ubuntu-python:20.04-3.7
        uses: docker/build-push-action@v2
        with:
          context: python/python-3.7-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-python:20.04-3.7
          push: true

      - name: Build & publish spaces-ubuntu-python:focal-3.7
        uses: docker/build-push-action@v2
        with:
          context: python/python-3.7-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-python:focal-3.7
          push: true

      - name: Build & publish spaces-ubuntu-python:20.04-3.8
        uses: docker/build-push-action@v2
        with:
          context: python/python-3.8-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-python:20.04-3.8
          push: true

      - name: Build & publish spaces-ubuntu-python:focal-3.8
        uses: docker/build-push-action@v2
        with:
          context: python/python-3.8-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-python:focal-3.8
          push: true

      - name: Build & publish spaces-ubuntu-python:20.04-3.9
        uses: docker/build-push-action@v2
        with:
          context: python/python-3.9-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-python:20.04-3.9
          push: true

      - name: Build & publish spaces-ubuntu-python:focal-3.9
        uses: docker/build-push-action@v2
        with:
          context: python/python-3.9-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-python:focal-3.9
          push: true
