name: Build & publish all images (on workflow change)

on:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/build_and_publish_all_images.yaml'

jobs:
  build_and_publish_all_images:
    uses: itopia-inc/spaces-images/.github/workflows/build_and_publish_all_images@main
