name: Build & publish changed images

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2 # This is for changed-files.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v1.1.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Sign in to GitHub Packages Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & publish ubuntu-node:20.04-12
        if: contains(steps.changed-files.outputs.modified_files, 'node/node-12-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: node/node-12-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-node:20.04-12
          push: true

      - name: Build & publish ubuntu-node:focal-12
        if: contains(steps.changed-files.outputs.modified_files, 'node/node-12-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: node/node-12-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-node:focal-12
          push: true

      - name: Build & publish ubuntu-node:20.04-14
        if: contains(steps.changed-files.outputs.modified_files, 'node/node-14-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: node/node-14-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-node:20.04-14
          push: true

      - name: Build & publish ubuntu-node:focal-14
        if: contains(steps.changed-files.outputs.modified_files, 'node/node-14-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: node/node-14-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-node:focal-14
          push: true

      - name: Build & publish ubuntu-node:20.04-16
        if: contains(steps.changed-files.outputs.modified_files, 'node/node-16-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: node/node-16-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-node:20.04-16
          push: true

      - name: Build & publish ubuntu-node:focal-16
        if: contains(steps.changed-files.outputs.modified_files, 'node/node-16-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: node/node-16-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-node:focal-16
          push: true

      - name: Build & publish ubuntu-openjdk:20.04-8
        if: contains(steps.changed-files.outputs.modified_files, 'openjdk/openjdk-8-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: openjdk/openjdk-8-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-openjdk:20.04-8
          push: true

      - name: Build & publish ubuntu-openjdk:focal-8
        if: contains(steps.changed-files.outputs.modified_files, 'openjdk/openjdk-8-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: openjdk/openjdk-8-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-openjdk:focal-8
          push: true

      - name: Build & publish ubuntu-openjdk:20.04-11
        if: contains(steps.changed-files.outputs.modified_files, 'openjdk/openjdk-11-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: openjdk/openjdk-11-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-openjdk:20.04-11
          push: true

      - name: Build & publish ubuntu-openjdk:focal-11
        if: contains(steps.changed-files.outputs.modified_files, 'openjdk/openjdk-11-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: openjdk/openjdk-11-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-openjdk:focal-11
          push: true

      - name: Build & publish ubuntu-python:20.04-2.7
        if: contains(steps.changed-files.outputs.modified_files, 'python/python-2.7-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: python/python-2.7-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-python:20.04-2.7
          push: true

      - name: Build & publish ubuntu-python:focal-2.7
        if: contains(steps.changed-files.outputs.modified_files, 'python/python-2.7-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: python/python-2.7-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-python:focal-2.7
          push: true

      - name: Build & publish ubuntu-python:20.04-3.6
        if: contains(steps.changed-files.outputs.modified_files, 'python/python-3.6-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: python/python-3.6-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-python:20.04-3.6
          push: true

      - name: Build & publish ubuntu-python:focal-3.6
        if: contains(steps.changed-files.outputs.modified_files, 'python/python-3.6-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: python/python-3.6-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-python:focal-3.6
          push: true

      - name: Build & publish ubuntu-python:20.04-3.7
        if: contains(steps.changed-files.outputs.modified_files, 'python/python-3.7-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: python/python-3.7-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-python:20.04-3.7
          push: true

      - name: Build & publish ubuntu-python:focal-3.7
        if: contains(steps.changed-files.outputs.modified_files, 'python/python-3.7-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: python/python-3.7-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-python:focal-3.7
          push: true

      - name: Build & publish ubuntu-python:20.04-3.8
        if: contains(steps.changed-files.outputs.modified_files, 'python/python-3.8-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: python/python-3.8-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-python:20.04-3.8
          push: true

      - name: Build & publish ubuntu-python:focal-3.8
        if: contains(steps.changed-files.outputs.modified_files, 'python/python-3.8-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: python/python-3.8-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-python:focal-3.8
          push: true

      - name: Build & publish ubuntu-python:20.04-3.9
        if: contains(steps.changed-files.outputs.modified_files, 'python/python-3.9-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: python/python-3.9-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-python:20.04-3.9
          push: true

      - name: Build & publish ubuntu-python:focal-3.9
        if: contains(steps.changed-files.outputs.modified_files, 'python/python-3.9-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: python/python-3.9-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-python:focal-3.9
          push: true
