name: 'Trigger: Source change PR'

on:
  pull_request:
    branches:
    - main
    paths:
    - 'complete-setups/**'
    - 'IDEs/**'
    - 'runtimes/**'

jobs:

  build_and_publish_all_dev_images:
    uses: itopia-inc/spaces-images/.github/workflows/build_and_publish_all_images.yaml@main
    with:
      environment: "dev"

  build_and_publish_all_prod_images:
    uses: itopia-inc/spaces-images/.github/workflows/build_and_publish_all_images.yaml@main
    with:
      environment: "prod"
